[2024-03-24 08:38:48,206] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:37:00+00:00 [queued]>
[2024-03-24 08:38:48,218] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:37:00+00:00 [queued]>
[2024-03-24 08:38:48,219] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:38:48,220] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-03-24 08:38:48,220] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:38:48,240] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): transform_all> on 2024-03-24T08:37:00+00:00
[2024-03-24 08:38:48,248] {standard_task_runner.py:52} INFO - Started process 16702 to run task
[2024-03-24 08:38:48,252] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'transform_all', '2024-03-24T08:37:00+00:00', '--job-id', '746', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/file.py', '--cfg-path', '/tmp/tmpt0xxzphr', '--error-file', '/tmp/tmpvu3bfn46']
[2024-03-24 08:38:48,253] {standard_task_runner.py:77} INFO - Job 746: Subtask transform_all
[2024-03-24 08:38:48,318] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:37:00+00:00 [running]> on host ce3400b6b8c4
[2024-03-24 08:38:48,401] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=transform_all
AIRFLOW_CTX_EXECUTION_DATE=2024-03-24T08:37:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-24T08:37:00+00:00
[2024-03-24 08:38:48,516] {python.py:151} INFO - Done. Returned value was: None
[2024-03-24 08:38:48,536] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=transform_all, execution_date=20240324T083700, start_date=20240324T083848, end_date=20240324T083848
[2024-03-24 08:38:48,608] {taskinstance.py:1265} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-03-24 08:38:48,671] {local_task_job.py:151} INFO - Task exited with return code 0
