[2024-03-24 08:41:09,623] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:40:00+00:00 [queued]>
[2024-03-24 08:41:09,697] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:40:00+00:00 [queued]>
[2024-03-24 08:41:09,714] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:41:09,721] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-03-24 08:41:09,722] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:41:09,913] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): transform_all> on 2024-03-24T08:40:00+00:00
[2024-03-24 08:41:09,922] {standard_task_runner.py:52} INFO - Started process 16954 to run task
[2024-03-24 08:41:09,929] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'transform_all', '2024-03-24T08:40:00+00:00', '--job-id', '775', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/file.py', '--cfg-path', '/tmp/tmpfdnx58wv', '--error-file', '/tmp/tmptbe23pk0']
[2024-03-24 08:41:09,930] {standard_task_runner.py:77} INFO - Job 775: Subtask transform_all
[2024-03-24 08:41:10,154] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:40:00+00:00 [running]> on host ce3400b6b8c4
[2024-03-24 08:41:10,563] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=transform_all
AIRFLOW_CTX_EXECUTION_DATE=2024-03-24T08:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-24T08:40:00+00:00
[2024-03-24 08:41:13,150] {python.py:151} INFO - Done. Returned value was: None
[2024-03-24 08:41:13,183] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=transform_all, execution_date=20240324T084000, start_date=20240324T084109, end_date=20240324T084113
[2024-03-24 08:41:13,284] {taskinstance.py:1265} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-03-24 08:41:13,336] {local_task_job.py:151} INFO - Task exited with return code 0
