[2024-03-24 04:57:10,350] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T04:55:00+00:00 [queued]>
[2024-03-24 04:57:10,409] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T04:55:00+00:00 [queued]>
[2024-03-24 04:57:10,410] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 04:57:10,411] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-03-24 04:57:10,411] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 04:57:10,526] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-03-24T04:55:00+00:00
[2024-03-24 04:57:10,546] {standard_task_runner.py:52} INFO - Started process 2758 to run task
[2024-03-24 04:57:10,590] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'get_weather_data', '2024-03-24T04:55:00+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/file.py', '--cfg-path', '/tmp/tmpdqix0fwc', '--error-file', '/tmp/tmpuaja57j2']
[2024-03-24 04:57:10,605] {standard_task_runner.py:77} INFO - Job 35: Subtask get_weather_data
[2024-03-24 04:57:11,219] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T04:55:00+00:00 [running]> on host ce3400b6b8c4
[2024-03-24 04:57:11,637] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=get_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-24T04:55:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-24T04:55:00+00:00
[2024-03-24 04:57:12,291] {python.py:151} INFO - Done. Returned value was: None
[2024-03-24 04:57:12,335] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=get_weather_data, execution_date=20240324T045500, start_date=20240324T045710, end_date=20240324T045712
[2024-03-24 04:57:12,385] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-24 04:57:12,416] {local_task_job.py:151} INFO - Task exited with return code 0
